#!/usr/bin/env python

import pygtk
pygtk.require20()
import gtk

from twisted.internet import gtk2reactor
gtk2reactor.install()


def main():
    builder = gtk.Builder()
    builder.add_from_file('ui/main.glade')

    signals = {'on_quit_mi_activate': gtk.main_quit,
               'on_connect_mi_activate': lambda widget, *data: None,
               'on_disconnect_mi_activate': lambda widget, *data: None,
               'on_config_mi_activate': lambda widget, *data: None,
               'on_new_channel_mi_activate': lambda widget, *data: None,
               'on_del_channel_mi_activate': lambda widget, *data: None,
               'on_refresh_mi_activate': lambda widget, *data: None,
               'on_about_mi_activate': lambda widget, *data: None}

    builder.connect_signals(signals)

    main_window = builder.get_object('main_window')
    main_window.connect('destroy', gtk.main_quit)
    main_window.show_all()

    gtk.main()

if __name__ == '__main__':
    main()
